### PR TITLE
Add more translatable Texts

### PR DESCRIPTION
**Pull request by 648480505**

### CODE REVIEW

**Comment by zoff99** [comment]
on some files you need to add the import:
https://github.com/Zoxcore/trifa_material/blob/0957c28fcdab4b779801007ca0678083a8647366/src/main/kotlin/org/briarproject/briar/desktop/contact/ContactItemView.kt#L55
where it is not already imported.

**Comment by zoff99** [comment]
@648480505 are you still working in this PR? there are a few unfinished things

**Comment by 648480505** [comment]
> @648480505 你还在做这个公关吗？ 还有一些未完成的事情

Because I haven't finished translating?

**Comment by zoff99** [comment]
these

```
ui.setting.open_data=Open data directory
ui.setting.nodes_updated=Bootstrap nodes updated from internet
ui.setting.update_bootstrap=update bootstrap nodes from internet
ui.setting.open_files=Open files directly instead of showing the containing directory.\nthis can be potentially dangerous!
ui.setting.enable_notifications=enable notifications
ui.setting.push_notifications=send push notifications
ui.setting.ToxProxies=Use ToxProxies of Friends
ui.setting.udp_mode=UDP mode
ui.setting.lan_discovery=LAN discovery
ui.setting.tor_proxy=use Tor proxy [on localhost port: 9050
ui.setting.changed_name=You have changed your own name
ui.setting.error_while_trying=Error while trying to set your own name
ui.setting.update_name=Update your Name
ui.setting.add_toxproxy=Add or Update your own Relay (ToxProxy)
```

are in the properties files but not used anywhere in the code. i can't merge it like this

**Comment by zoff99** [comment]
i remove the unused ones for now and merging what we have. if you want to translate some more you can add to this branch or make a new PR

**Pull request merged**
