### PR TITLE
Add more translatable Texts

### PR DESCRIPTION
**Pull request by 648480505**
[supplement](https://github.com/Zoxcore/trifa_material/pull/227)

### CODE REVIEW

**Comment by zoff99** [comment]
ui.setting.ToxProxies --> keep keys lowercase please
ui.setting.tor_proxy --> the closing bracket is missing

**Comment by zoff99** [comment]
``` file:///home/runner/work/trifa_material/trifa_material/src/main/kotlin/org/briarproject/briar/desktop/SettingDetails.kt:137:49 Syntax error: Expecting ')'.
 file:///home/runner/work/trifa_material/trifa_material/src/main/kotlin/org/briarproject/briar/desktop/SettingDetails.kt:554:49 Syntax error: Expecting '"'.
 file:///home/runner/work/trifa_material/trifa_material/src/main/kotlin/org/briarproject/briar/desktop/SettingDetails.kt:554:49 Syntax error: Expecting ')'.
 file:///home/runner/work/trifa_material/trifa_material/src/main/kotlin/org/briarproject/briar/desktop/SettingDetails.kt:554:49 Syntax error: Incorrect template entry: .
```

**Comment by 648480505** [comment]
> ```
>  file:///home/runner/work/trifa_material/trifa_material/src/main/kotlin/org/briarproject/briar/desktop/SettingDetails.kt:554:49 Syntax error: Expecting '"'.
>  file:///home/runner/work/trifa_material/trifa_material/src/main/kotlin/org/briarproject/briar/desktop/SettingDetails.kt:554:49 Syntax error: Expecting ')'.
>  file:///home/runner/work/trifa_material/trifa_material/src/main/kotlin/org/briarproject/briar/desktop/SettingDetails.kt:554:49 Syntax error: Incorrect template entry: .
> ```

Error fixed

**Comment by zoff99** [comment]
file:///home/runner/work/trifa_material/trifa_material/src/main/kotlin/org/briarproject/briar/desktop/SettingDetails.kt:137:49 Syntax error: Expecting ')'.

still 1 missing

**Pull request merged**
